### PR TITLE
My Ruby Enumerable Methods Project

### PR DESCRIPTION
**Pull request by edieatha**
## Request code review for enumerable-methods.
✅ Created a script file to house my methods and ran it in IRB to test them.
✅ Added your new methods onto the existing Enumerable module.
✅ Tested my #my_inject with #multiply_els method. 
✅ Modified #my_map method to take a proc instead.
✅ Modify your #my_map method to take either a proc or a block.

### CODE REVIEW

**Review by serdg0 — CHANGES_REQUESTED** [review]
Hi @edieatha !
Great work, it's clear that you have a grasp on enumerators. But there are some cases we need to check before approving your project. Here they are:

**my_each & my_each_with_index**

- [x] Should return the array itself when a block is given.

**my_select**

- [x] Should return an enumerator when no block is given.

**my_all & my_any**

- [ ] Should return true if it nevers return nil or false(for  my_all) & or if it ever returns false or nil (if my_all), even when no block is given.

- [ ] Should contemplate class and return true if all of the collection is a member of the same class for my_all and true if at least one of the collection is memeber of that class (my_any).

- [ ] Both should be able to test regex (collection match a regex pattern).

**my_none**

- [ ] When no block is given should return true only if none of the collection is true.

- [ ] Should be able to test regex (collection match a regex pattern).

**my_count**

- [ ] When an argument is given it should count the number of items that are equal to the given item.

**my_map**

- [ ] When a proc/argument is passed it should return a new array with the result of running the proc/argument once for every element.

- [ ] If a block and proc are given it should only run the proc.

- [ ] my_map shouldnt mutate the original array.

**my_inject**

- [ ] Consider when a symbol is passed directly to thr method.

- [ ] Tested with a big range looking for it product, and it returned 0 (even when started in a non-cero accmulator), so is not properly combined all the elements.

Fix the above issues and submit for another CRR.

**Happy Coding!** :computer: :nerd_face:
**_Sergio Diaz_**

**Comment by edieatha** [comment]
## TSE Code Review Adjustments
✅ my_each & my_each_with_index 
👍 returns an array itself when block is given.
✅ my_select 
👍 returns an enumerator when no block is given.
✅ my_all, my_any & my_none
✅ my_count & my_map
✅ my_inject

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team!
### You have done a great job so far :clap: However, you have a few issues to address before your project could be approved.
-[ ] my_map method is not working correctly when I run the test
my_map
- [ ] my_none test case is not passing 
my_none
- [ ] my_any test cases are not passing
my_any
### Make these changes and request for another code request. Good luck.
- Happy coding!

By Raymond
slack @iamraymond

**Review by rOluochKe — APPROVED** [review]
Hello Team!
### You have done a great job and for also implementing changes from the previous reviews :clap: The project looks good and therefore, it has been approved. Congratulations :boom: :100:
### You can merge and submit a project completion form from the dashboard. Good luck with the next project.
- Happy coding!

**Pull request merged**
